#!/usr/bin/env python3

import os,sys, re
from constant import *

component_designation={
  CAT_SMD_CAPACITOR: 'C',
  CAT_SMD_RESISTOR: 'R',
  CAT_SMD_INDUCTOR: 'L',
  CAT_SMD_LED: 'D',
  CAT_SMD_DIODE: 'D',
  CAT_SMD_LDO_LOW_DROPOUT_LINEAR_REGULATION: "U",

  # CAT_SMD_ACTIVE_FILTER: active_filter_footprint_list_expand,
  # CAT_SMD_AMBIENT_LIGHT_SENSOR: ambient_light_sensor_footprint_list_expand,
  # CAT_SMD_AMPLIFIER: amplifier_footprint_list_expand,
  # CAT_SMD_ANALOG_SWITCH_CHIP: analog_switch_chip_footprint_list_expand,
  # CAT_SMD_ANALOG_TO_DIGITAL_CONVERSION_CHIP: analog_to_digital_conversion_chip_footprint_list_expand,
  # CAT_SMD_ANGLE_SENSOR: angle_sensor_footprint_list_expand,
  # CAT_SMD_ANGULAR_VELOCITY_SENSOR: angular_velocity_sensor_footprint_list_expand,
  # CAT_SMD_ATTITUDE_SENSOR: attitude_sensor_footprint_list_expand,
  # CAT_SMD_AUDIO_POWER_AMPLIFIER: audio_power_amplifier_footprint_list_expand,
  # CAT_SMD_AVALANCHE_DIODE: avalanche_diode_footprint_list_expand,
  # CAT_SMD_BALANCED_UNBALANCED_TRANSFORMER: balanced_unbalanced_transformer_footprint_list_expand,
  # CAT_SMD_BALLAST_CONTROLLER: ballast_controller_footprint_list_expand,
  # CAT_SMD_BATTERY_BOX_BATTERY_HOLDER: battery_box_battery_holder_footprint_list_expand,
  # CAT_SMD_BATTERY_POWER_MANAGEMENT_CHIP: battery_power_management_chip_footprint_list_expand,
  # CAT_SMD_BATTERY_PROTECTION_CHIP: battery_protection_chip_footprint_list_expand,
  # CAT_SMD_BUFFERS_DRIVERS_RECEIVERS_TRANSCEIVERS: buffers_drivers_receivers_transceivers_footprint_list_expand,
  # CAT_SMD_CAN_CHIP: can_chip_footprint_list_expand,
  # CAT_SMD_CAPACITOR: capacitor_footprint_list_expand,
  # CAT_SMD_CERAMIC_RESONATOR: ceramic_resonator_footprint_list_expand,
  # CAT_SMD_CLOCK_BUFFER_DRIVER: clock_buffer_driver_footprint_list_expand,
  # CAT_SMD_CLOCK_GENERATOR_PLL_FREQUENCY_SYNTHESIZER: clock_generator_pll_frequency_synthesizer_footprint_list_expand,
  # CAT_SMD_CLOCK_TIMING_DEDICATED: clock_timing_dedicated_footprint_list_expand,
  # CAT_SMD_CODEC_CHIP: codec_chip_footprint_list_expand,
  # CAT_SMD_COLOR_SENSOR: color_sensor_footprint_list_expand,
  # CAT_SMD_COMMON_MODE_INDUCTOR_FILTER: common_mode_inductor_filter_footprint_list_expand,
  # CAT_SMD_CONSTANT_CURRENT_DIODE: constant_current_diode_footprint_list_expand,
  # CAT_SMD_CONSTANT_CURRENT_DIODE: constant_current_diode_footprint_list_expand,
  # CAT_SMD_COUNTER_DIVIDER: counter_divider_footprint_list_expand,
  # CAT_SMD_CPLD_FPGA_CHIP: cpld_fpga_chip_footprint_list_expand,
  # CAT_SMD_CURRENT_MONITORING_CHIP: current_monitoring_chip_footprint_list_expand,
  # CAT_SMD_CURRENT_SENSOR: current_sensor_footprint_list_expand,
  # CAT_SMD_DARLINGTON_TRANSISTOR_ARRAY_DRIVE: darlington_transistor_array_drive_footprint_list_expand,
  # CAT_SMD_DARLINGTON: darlington_footprint_list_expand,
  # CAT_SMD_DC_DC_CHIP: dc_dc_chip_footprint_list_expand,
  # CAT_SMD_DDR_MEMORY: ddr_memory_footprint_list_expand,
  # CAT_SMD_DDS_CHIP: dds_chip_footprint_list_expand,
  # CAT_SMD_DEDICATED_SENSORS: dedicated_sensors_footprint_list_expand,
  # CAT_SMD_DIFFERENTIAL_OP_AMPS: differential_op_amps_footprint_list_expand,
  # CAT_SMD_DIGITAL_POTENTIOMETER_CHIP: digital_potentiometer_chip_footprint_list_expand,
  # CAT_SMD_DIGITAL_TO_ANALOG_CONVERSION_CHIP: digital_to_analog_conversion_chip_footprint_list_expand,
  # CAT_SMD_DIODE: diode_footprint_list_expand,
  # CAT_SMD_DISCHARGE_TUBE: discharge_tube_footprint_list_expand,
  # CAT_SMD_DRIVER_CHIP: driver_chip_footprint_list_expand,
  # CAT_SMD_EEPROM_MEMORY: eeprom_memory_footprint_list_expand,
  # CAT_SMD_EL_DRIVE: el_drive_footprint_list_expand,
  # CAT_SMD_ELECTROLYTIC_CAPACITORS: electrolytic_capacitors_footprint_list_expand,
  # CAT_SMD_EMI_RFI_FILTERS_LC_RC_NETWORKS: emi_rfi_filters_lc_rc_networks_footprint_list_expand,
  # CAT_SMD_EPROM_MEMORY: eprom_memory_footprint_list_expand,
  CAT_SMD_ESD_DIODE: 'D',
  # CAT_SMD_ETHERNET_CHIP: ethernet_chip_footprint_list_expand,
  # CAT_SMD_FAST_RECOVERY_DIODE: fast_recovery_diode_footprint_list_expand,
  # CAT_SMD_FAST_RECOVERY_DIODE: fast_recovery_diode_footprint_list_expand,
  # CAT_SMD_FET_INPUT_OP_AMP: fet_input_op_amp_footprint_list_expand,
  # CAT_SMD_FLASH_MEMORY: flash_memory_footprint_list_expand,
  # CAT_SMD_FONT_CHIP: font_chip_footprint_list_expand,
  # CAT_SMD_FRAM_MEMORY: fram_memory_footprint_list_expand,
  # CAT_SMD_FUEL_GAUGE_CHIP: fuel_gauge_chip_footprint_list_expand,
  # CAT_SMD_FULL_BRIDGE_HALF_BRIDGE_DRIVE: full_bridge_half_bridge_drive_footprint_list_expand,
  # CAT_SMD_GAS_SENSOR: gas_sensor_footprint_list_expand,
  # CAT_SMD_GATE_AND_INVERTER: gate_and_inverter_footprint_list_expand,
  # CAT_SMD_HF_INDUCTOR: hf_inductor_footprint_list_expand,
  # CAT_SMD_HIGH_EFFICIENCY_DIODE: high_efficiency_diode_footprint_list_expand,
  # CAT_SMD_HIGH_PRESISION_RESISTOR: high_presision_resistor_footprint_list_expand,
  # CAT_SMD_HIGH_SPEED_BROADBAND_OP_AMP: high_speed_broadband_op_amp_footprint_list_expand,
  # CAT_SMD_HIGH_VOLTAGE_RESISTOR: high_voltage_resistor_footprint_list_expand,
  # CAT_SMD_I_O_EXPANDER: i_o_expander_footprint_list_expand,
  # CAT_SMD_IGBT_DRIVE: igbt_drive_footprint_list_expand,
  # CAT_SMD_IGBT_TUBE: igbt_tube_footprint_list_expand,
  # CAT_SMD_INDUCTOR: inductor_footprint_list_expand,
  # CAT_SMD_INFRARED_EMISSION_TUBE: infrared_emission_tube_footprint_list_expand,
  # CAT_SMD_INFRARED_RECEIVER_TUBE: infrared_receiver_tube_footprint_list_expand,
  # CAT_SMD_INFRARED_SENSOR: infrared_sensor_footprint_list_expand,
  # CAT_SMD_INSTRUMENT_OPERATIONAL_AMPLIFIER: instrument_operational_amplifier_footprint_list_expand,
  # CAT_SMD_INTERFACE_CHIP: interface_chip_footprint_list_expand,
  # CAT_SMD_INTERFACE_CONTROLLER: interface_controller_footprint_list_expand,
  # CAT_SMD_INTERFACE_DEDICATED: interface_dedicated_footprint_list_expand,
  # CAT_SMD_INTERFACE_LIN_TRANSCEIVER: interface_lin_transceiver_footprint_list_expand,
  # CAT_SMD_INTERFACE_TELECOM: interface_telecom_footprint_list_expand,
  # CAT_SMD_ISOLATOR_CHIP: isolator_chip_footprint_list_expand,
  # CAT_SMD_JFET_JUNCTION_FIELD_EFFECT_TRANSISTOR: jfet_junction_field_effect_transistor_footprint_list_expand,
  # CAT_SMD_LATCHES: latches_footprint_list_expand,
  # CAT_SMD_LCD_DRIVER: lcd_driver_footprint_list_expand,

  # CAT_SMD_LED_DRIVE: led_drive_footprint_list_expand,
  # CAT_SMD_LED_RESISTOR: led_resistor_footprint_list_expand,
  # CAT_SMD_LED: led_footprint_list_expand,
  # CAT_SMD_LEVEL_SHIFTER_SHIFTER: level_shifter_shifter_footprint_list_expand,
  # CAT_SMD_LINEAR_VOLTAGE_REGULATOR_CHIP: linear_voltage_regulator_chip_footprint_list_expand,
  # CAT_SMD_LOGIC_CHIP_: logic_chip__footprint_list_expand,
  # CAT_SMD_LOGIC_CHIP_4000_SERIES: logic_chip_4000_series_footprint_list_expand,
  # CAT_SMD_LOGIC_CHIP_74_SERIES: logic_chip_74_series_footprint_list_expand,
  # CAT_SMD_LOW_NOISE_OP_AMP: low_noise_op_amp_footprint_list_expand,
  # CAT_SMD_LOW_POWER_OP_AMP: low_power_op_amp_footprint_list_expand,
  # CAT_SMD_LVDS_CHIP: lvds_chip_footprint_list_expand,
  # CAT_SMD_MAGNETIC_SENSOR: magnetic_sensor_footprint_list_expand,
  # CAT_SMD_MCU_MONITORING_CHIP: mcu_monitoring_chip_footprint_list_expand,
  # CAT_SMD_MICROCONTROLLER_MCU: microcontroller_mcu_footprint_list_expand,
  # CAT_SMD_MOS_DRIVE: mos_drive_footprint_list_expand,
  # CAT_SMD_MOS_FIELD_EFFECT_TUBE: mos_field_effect_tube_footprint_list_expand,
  # CAT_SMD_MOTOR_DRIVER: motor_driver_footprint_list_expand,
  # CAT_SMD_MULTI_FREQUENCY_OSCILLATOR: multi_frequency_oscillator_footprint_list_expand,
  # CAT_SMD_NETWORK_PORT_TRANSFORMER: network_port_transformer_footprint_list_expand,
  # CAT_SMD_NIOBIUM_OXIDE_CAPACITOR: niobium_oxide_capacitor_footprint_list_expand,
  # CAT_SMD_NTC_RESISTOR: ntc_resistor_footprint_list_expand,
  # CAT_SMD_OP_AMP_GENERAL_OP_AMP: op_amp_general_op_amp_footprint_list_expand,
  # CAT_SMD_OP_AMP_PRECISION_OP_AMP: op_amp_precision_op_amp_footprint_list_expand,
  # CAT_SMD_OPTICAL_SENSORS: optical_sensors_footprint_list_expand,
  # CAT_SMD_PHOTOELECTRIC_SOLID_STATE_RELAY: photoelectric_solid_state_relay_footprint_list_expand,
  # CAT_SMD_PHOTOELECTRIC_SWITCH: photoelectric_switch_footprint_list_expand,
  # CAT_SMD_PHOTOELECTRIC_TRIAC: photoelectric_triac_footprint_list_expand,
  # CAT_SMD_PORT_EXPANSION_CHIP: port_expansion_chip_footprint_list_expand,
  # CAT_SMD_POSITION_SENSOR: position_sensor_footprint_list_expand,
  # CAT_SMD_POWER_INDUCTOR: power_inductor_footprint_list_expand,
  # CAT_SMD_POWER_MONITORING_CHIP: power_monitoring_chip_footprint_list_expand,
  # CAT_SMD_POWER_SWITCH_CHIP: power_switch_chip_footprint_list_expand,
  # CAT_SMD_PRESSURE_SENSOR: pressure_sensor_footprint_list_expand,
  # CAT_SMD_PROFESSIONAL_POWER_MANAGEMENT_PMIC: professional_power_management_pmic_footprint_list_expand,
  # CAT_SMD_PTC_RESETTABLE_FUSE: ptc_resettable_fuse_footprint_list_expand,
  # CAT_SMD_REAL_TIME_CLOCK_CHIP: real_time_clock_chip_footprint_list_expand,
  # CAT_SMD_RECTIFIER_BRIDGE: rectifier_bridge_footprint_list_expand,
  # CAT_SMD_RESISTOR_NETWORK: resistor_network_footprint_list_expand,
  # CAT_SMD_RESISTOR: resistor_footprint_list_expand,
  # CAT_SMD_RF_AMPLIFIER: rf_amplifier_footprint_list_expand,
  # CAT_SMD_RF_ATTENUATOR: rf_attenuator_footprint_list_expand,
  # CAT_SMD_RF_CARD_CHIP: rf_card_chip_footprint_list_expand,
  # CAT_SMD_RF_COUPLER: rf_coupler_footprint_list_expand,
  # CAT_SMD_RF_DETECTOR: rf_detector_footprint_list_expand,
  # CAT_SMD_RF_FILTER: rf_filter_footprint_list_expand,
  # CAT_SMD_RF_MIXER: rf_mixer_footprint_list_expand,
  # CAT_SMD_RF_SWITCH: rf_switch_footprint_list_expand,
  # CAT_SMD_RS232_CHIP: rs232_chip_footprint_list_expand,
  # CAT_SMD_RS485_RS422_CHIP: rs485_rs422_chip_footprint_list_expand,
  # CAT_SMD_SCHOTTKY_DIODE: schottky_diode_footprint_list_expand,
  # CAT_SMD_SDRAM_MEMORY: sdram_memory_footprint_list_expand,
  # CAT_SMD_SECOND_CLASSIFICATION_OF_ENGINEERING_DEPARTMENT_DATA: second_classification_of_engineering_department_data_footprint_list_expand,
  # CAT_SMD_SECURITY_VERIFICATION_ENCRYPTION_CHIP: security_verification_encryption_chip_footprint_list_expand,
  # CAT_SMD_SENSOR_INTERFACE_CHIP: sensor_interface_chip_footprint_list_expand,
  # CAT_SMD_SERIAL_INTERFACE: serial_interface_footprint_list_expand,
  # CAT_SMD_SHIFT_REGISTER: shift_register_footprint_list_expand,
  # CAT_SMD_SIGNAL_BUFFERS_REPEATERS_DISTRIBUTORS: signal_buffers_repeaters_distributors_footprint_list_expand,
  # CAT_SMD_SIGNAL_SWITCHES_MULTIPLEXERS_DECODERS: signal_switches_multiplexers_decoders_footprint_list_expand,
  # CAT_SMD_SMD_ACTIVE_CRYSTAL_OSCILLATOR: smd_active_crystal_oscillator_footprint_list_expand,
  # CAT_SMD_DISPOSABLE_FUSES: disposable_fuses_footprint_list_expand,
  # CAT_SMD_MAGNETIC_BEADS: magnetic_beads_footprint_list_expand,
  # CAT_SMD_OPTOCOUPLER: optocoupler_footprint_list_expand,
  # CAT_SMD_PASSIVE_CRYSTAL_RESONATOR: passive_crystal_resonator_footprint_list_expand,
  # CAT_SMD_SOLID_ELECTROLYTIC_CAPACITOR: solid_electrolytic_capacitor_footprint_list_expand,
  # CAT_SMD_SOUND_SURFACE_RESONATOR_SAW: sound_surface_resonator_saw_footprint_list_expand,
  # CAT_SMD_SPECIAL_FUNCTION_AMPLIFIER: special_function_amplifier_footprint_list_expand,
  # CAT_SMD_SPECIAL_FUNCTION_DRIVEN: special_function_driven_footprint_list_expand,
  # CAT_SMD_SRAM_MEMORY: sram_memory_footprint_list_expand,
  # CAT_SMD_SWITCHING_DIODE: switching_diode_footprint_list_expand,
  # CAT_SMD_SWITCHING_POWER_CHIP: switching_power_chip_footprint_list_expand,
  # CAT_SMD_TACT_SWITCH: tact_switch_footprint_list_expand,
  # CAT_SMD_TANTALUM_CAPACITOR: tantalum_capacitor_footprint_list_expand,
  # CAT_SMD_TEMPERATURE_AND_HUMIDITY_SENSOR: temperature_and_humidity_sensor_footprint_list_expand,
  # CAT_SMD_TEMPERATURE_SENSOR: temperature_sensor_footprint_list_expand,
  # CAT_SMD_THYRISTOR: thyristor_footprint_list_expand,
  # CAT_SMD_TIME_BASE_INTEGRATED_CHIP: time_base_integrated_chip_footprint_list_expand,
  # CAT_SMD_TOUCH_CHIP: touch_chip_footprint_list_expand,
  # CAT_SMD_TOUCH_SCREEN_CONTROLLER: touch_screen_controller_footprint_list_expand,
  # CAT_SMD_TRIGGER_DIODE: trigger_diode_footprint_list_expand,
  # CAT_SMD_TRIGGER: trigger_footprint_list_expand,
  # CAT_SMD_TRIODE_DIGITAL_TRIODE: triode_digital_triode_footprint_list_expand,
  # CAT_SMD_TRIODE: triode_footprint_list_expand,
  # CAT_SMD_TVS_DIODE: tvs_diode_footprint_list_expand,
  # CAT_SMD_ULTRA_FAST_RECOVERY_DIODE: ultra_fast_recovery_diode_footprint_list_expand,
  # CAT_SMD_USB_CHIP: usb_chip_footprint_list_expand,
  # CAT_SMD_VARICAP_DIODE: varicap_diode_footprint_list_expand,
  # CAT_SMD_VARISTOR: varistor_footprint_list_expand,
  # CAT_SMD_VIDEO_AND_AUDIO_INTERFACE_CHIP: video_and_audio_interface_chip_footprint_list_expand,
  # CAT_SMD_VIDEO_FILTER_DRIVER: video_filter_driver_footprint_list_expand,
  # CAT_SMD_VOLTAGE_COMPARATOR: voltage_comparator_footprint_list_expand,
  # CAT_SMD_VOLTAGE_REFERENCE_CHIP: voltage_reference_chip_footprint_list_expand,
  # CAT_SMD_WIRELESS_TRANSCEIVER_CHIP: wireless_transceiver_chip_footprint_list_expand,
  # CAT_SMD_ZENER_DIODE: zener_diode_footprint_list_expand,

}

def lookup_component_designation(str_in):
  return component_designation[str_in]