#!/usr/bin/env python3
import os,sys,re
from constant import *


SMD_CAPACITOR_SYMBOL='''
P 2 0 1 13 -60 -20 60 -20 N
P 2 0 1 12 -60 20 60 20 N
X ~ 1 0 100 80 D 50 50 1 1 P
X ~ 2 0 -100 80 U 50 50 1 1 P
'''.strip()

SMD_RESISTOR_SYMBOL='''
S -30 70 30 -70 0 1 8 N
X ~ 1 0 100 30 D 50 50 1 1 P
X ~ 2 0 -100 30 U 50 50 1 1 P
'''.strip()

SMD_INDUCTOR_SYMBOL='''
A 0 -60 20 -899 899 0 1 0 N 0 -80 0 -40
A 0 -20 20 -899 899 0 1 0 N 0 -40 0 0
A 0 20 20 -899 899 0 1 0 N 0 0 0 40
A 0 60 20 -899 899 0 1 0 N 0 40 0 80
X ~ 1 0 100 20 D 50 50 1 1 P
X ~ 2 0 -100 20 U 50 50 1 1 P
'''.strip()

SMD_LED_SYMBOL='''
P 2 0 1 0 -30 -40 -30 40 N
P 2 0 1 0 40 0 -30 0 N
P 4 0 1 0 30 -40 -30 0 30 40 30 -40 N
P 5 0 1 0 0 30 -20 50 -10 50 -20 50 -20 40 N
P 5 0 1 0 20 50 0 70 10 70 0 70 0 60 N
X K 1 -100 0 70 R 50 50 1 1 P
X A 2 100 0 70 L 50 50 1 1 P
'''.strip()

SMD_DIODE_SYMBOL='''
P 2 0 1 0 -30 -40 -30 40 N
P 2 0 1 0 -30 0 30 0 N
P 4 0 1 0 30 -40 -30 0 30 40 30 -40 N
X K 1 -100 0 70 R 50 50 1 1 P
X A 2 100 0 70 L 50 50 1 1 P
'''.strip()

SMD_LDO_SYMBOL='''
S -200 -200 200 75 0 1 10 f
X ADJ 1 0 -300 100 U 50 50 1 1 I
X VO 2 300 0 100 L 50 50 1 1 w
X VI 3 -300 0 100 R 50 50 1 1 W
'''.strip()

SMD_MICROCONTROLLER_MCU_SYMBOL='''
T 0 0 -400 50 0 0 0 DEFAULT Normal 0 C C
S -800 800 750 -750 0 1 0 f
'''.strip()

SMD_DEFAULT_SYMBOL='''
T 0 0 -400 50 0 0 0 DEFAULT Normal 0 C C
S -800 800 750 -750 0 1 0 f
'''.strip()

ACTIVE_FILTER_SYMBOL=SMD_DEFAULT_SYMBOL
AMBIENT_LIGHT_SENSOR_SYMBOL=SMD_DEFAULT_SYMBOL
AMPLIFIER_SYMBOL=SMD_DEFAULT_SYMBOL
ANALOG_TO_DIGITAL_CONVERSION_CHIP_SYMBOL=SMD_DEFAULT_SYMBOL
ANGLE_SENSOR_SYMBOL=SMD_DEFAULT_SYMBOL
ANGULAR_VELOCITY_SENSOR_SYMBOL=SMD_DEFAULT_SYMBOL
ATTITUDE_SENSOR_SYMBOL=SMD_DEFAULT_SYMBOL
AUDIO_POWER_AMPLIFIER_SYMBOL=SMD_DEFAULT_SYMBOL
AVALANCHE_DIODE_SYMBOL=SMD_DEFAULT_SYMBOL
BALANCED_UNBALANCED_TRANSFORMER_SYMBOL=SMD_DEFAULT_SYMBOL
BALLAST_CONTROLLER_SYMBOL=SMD_DEFAULT_SYMBOL
BATTERY_BOX_BATTERY_HOLDER_SYMBOL=SMD_DEFAULT_SYMBOL
BATTERY_POWER_MANAGEMENT_CHIP_SYMBOL=SMD_DEFAULT_SYMBOL
BATTERY_PROTECTION_CHIP_SYMBOL=SMD_DEFAULT_SYMBOL
BUFFERS_DRIVERS_RECEIVERS_TRANSCEIVERS_SYMBOL=SMD_DEFAULT_SYMBOL
CAN_CHIP_SYMBOL=SMD_DEFAULT_SYMBOL
CAPACITOR_SYMBOL=SMD_DEFAULT_SYMBOL
CERAMIC_RESONATOR_SYMBOL=SMD_DEFAULT_SYMBOL
CLOCK_BUFFER_DRIVER_SYMBOL=SMD_DEFAULT_SYMBOL
CLOCK_GENERATOR_PLL_FREQUENCY_SYNTHESIZER_SYMBOL=SMD_DEFAULT_SYMBOL
CLOCK_TIMING_DEDICATED_SYMBOL=SMD_DEFAULT_SYMBOL
CODEC_CHIP_SYMBOL=SMD_DEFAULT_SYMBOL
COLOR_SENSOR_SYMBOL=SMD_DEFAULT_SYMBOL
COMMON_MODE_INDUCTOR_FILTER_SYMBOL=SMD_DEFAULT_SYMBOL
COUNTER_DIVIDER_SYMBOL=SMD_DEFAULT_SYMBOL
CPLD_FPGA_CHIP_SYMBOL=SMD_DEFAULT_SYMBOL
CURRENT_MONITORING_CHIP_SYMBOL=SMD_DEFAULT_SYMBOL
CURRENT_SENSOR_SYMBOL=SMD_DEFAULT_SYMBOL
DARLINGTON_TRANSISTOR_ARRAY_DRIVE_SYMBOL=SMD_DEFAULT_SYMBOL
DARLINGTON_SYMBOL=SMD_DEFAULT_SYMBOL
DC_DC_CHIP_SYMBOL=SMD_DEFAULT_SYMBOL
DDR_MEMORY_SYMBOL=SMD_DEFAULT_SYMBOL
DDS_CHIP_SYMBOL=SMD_DEFAULT_SYMBOL
DEDICATED_SENSORS_SYMBOL=SMD_DEFAULT_SYMBOL
DIFFERENTIAL_OP_AMPS_SYMBOL=SMD_DEFAULT_SYMBOL
DIGITAL_POTENTIOMETER_CHIP_SYMBOL=SMD_DEFAULT_SYMBOL
DIGITAL_TO_ANALOG_CONVERSION_CHIP_SYMBOL=SMD_DEFAULT_SYMBOL
DIODE_SYMBOL=SMD_DEFAULT_SYMBOL
DISCHARGE_TUBE_SYMBOL=SMD_DEFAULT_SYMBOL
DISPOSABLE_FUSES_SYMBOL=SMD_DEFAULT_SYMBOL
DRIVER_CHIP_SYMBOL=SMD_DEFAULT_SYMBOL
EEPROM_MEMORY_SYMBOL=SMD_DEFAULT_SYMBOL
EL_DRIVE_SYMBOL=SMD_DEFAULT_SYMBOL
ELECTROLYTIC_CAPACITORS_SYMBOL=SMD_DEFAULT_SYMBOL
EMI_RFI_FILTERS_LC_RC_NETWORKS_SYMBOL=SMD_DEFAULT_SYMBOL
EPROM_MEMORY_SYMBOL=SMD_DEFAULT_SYMBOL
ETHERNET_CHIP_SYMBOL=SMD_DEFAULT_SYMBOL
FAST_RECOVERY_DIODE_SYMBOL=SMD_DEFAULT_SYMBOL
FAST_RECOVERY_DIODE_SYMBOL=SMD_DEFAULT_SYMBOL
FET_INPUT_OP_AMP_SYMBOL=SMD_DEFAULT_SYMBOL
FLASH_MEMORY_SYMBOL=SMD_DEFAULT_SYMBOL
FONT_CHIP_SYMBOL=SMD_DEFAULT_SYMBOL
FRAM_MEMORY_SYMBOL=SMD_DEFAULT_SYMBOL
FUEL_GAUGE_CHIP_SYMBOL=SMD_DEFAULT_SYMBOL
FULL_BRIDGE_HALF_BRIDGE_DRIVE_SYMBOL=SMD_DEFAULT_SYMBOL
GAS_SENSOR_SYMBOL=SMD_DEFAULT_SYMBOL
GATE_AND_INVERTER_SYMBOL=SMD_DEFAULT_SYMBOL
HF_INDUCTOR_SYMBOL=SMD_DEFAULT_SYMBOL
HIGH_EFFICIENCY_DIODE_SYMBOL=SMD_DEFAULT_SYMBOL
HIGH_PRESISION_RESISTOR_SYMBOL=SMD_DEFAULT_SYMBOL
HIGH_SPEED_BROADBAND_OP_AMP_SYMBOL=SMD_DEFAULT_SYMBOL
HIGH_VOLTAGE_RESISTOR_SYMBOL=SMD_DEFAULT_SYMBOL
I_O_EXPANDER_SYMBOL=SMD_DEFAULT_SYMBOL
IGBT_DRIVE_SYMBOL=SMD_DEFAULT_SYMBOL
IGBT_TUBE_SYMBOL=SMD_DEFAULT_SYMBOL
INDUCTOR_SYMBOL=SMD_DEFAULT_SYMBOL
INFRARED_EMISSION_TUBE_SYMBOL=SMD_DEFAULT_SYMBOL
INFRARED_RECEIVER_TUBE_SYMBOL=SMD_DEFAULT_SYMBOL
INFRARED_SENSOR_SYMBOL=SMD_DEFAULT_SYMBOL
INSTRUMENT_OPERATIONAL_AMPLIFIER_SYMBOL=SMD_DEFAULT_SYMBOL
INTERFACE_CHIP_SYMBOL=SMD_DEFAULT_SYMBOL
INTERFACE_CONTROLLER_SYMBOL=SMD_DEFAULT_SYMBOL
INTERFACE_DEDICATED_SYMBOL=SMD_DEFAULT_SYMBOL
INTERFACE_LIN_TRANSCEIVER_SYMBOL=SMD_DEFAULT_SYMBOL
INTERFACE_TELECOM_SYMBOL=SMD_DEFAULT_SYMBOL
ISOLATOR_CHIP_SYMBOL=SMD_DEFAULT_SYMBOL
JFET_JUNCTION_FIELD_EFFECT_TRANSISTOR_SYMBOL=SMD_DEFAULT_SYMBOL
LATCHES_SYMBOL=SMD_DEFAULT_SYMBOL
LCD_DRIVER_SYMBOL=SMD_DEFAULT_SYMBOL
LED_DRIVE_SYMBOL=SMD_DEFAULT_SYMBOL
LED_RESISTOR_SYMBOL=SMD_DEFAULT_SYMBOL
LED_SYMBOL=SMD_DEFAULT_SYMBOL
LEVEL_SHIFTER_SHIFTER_SYMBOL=SMD_DEFAULT_SYMBOL
LINEAR_VOLTAGE_REGULATOR_CHIP_SYMBOL=SMD_DEFAULT_SYMBOL
LOGIC_CHIP__SYMBOL=SMD_DEFAULT_SYMBOL
LOGIC_CHIP_4000_SERIES_SYMBOL=SMD_DEFAULT_SYMBOL
LOGIC_CHIP_74_SERIES_SYMBOL=SMD_DEFAULT_SYMBOL
LOW_NOISE_OP_AMP_SYMBOL=SMD_DEFAULT_SYMBOL
LOW_POWER_OP_AMP_SYMBOL=SMD_DEFAULT_SYMBOL
LVDS_CHIP_SYMBOL=SMD_DEFAULT_SYMBOL
MAGNETIC_BEADS_SYMBOL=SMD_DEFAULT_SYMBOL
MAGNETIC_SENSOR_SYMBOL=SMD_DEFAULT_SYMBOL
MCU_MONITORING_CHIP_SYMBOL=SMD_DEFAULT_SYMBOL

MOS_DRIVE_SYMBOL=SMD_DEFAULT_SYMBOL
MOS_FIELD_EFFECT_TUBE_SYMBOL=SMD_DEFAULT_SYMBOL
MOTOR_DRIVER_SYMBOL=SMD_DEFAULT_SYMBOL
MULTI_FREQUENCY_OSCILLATOR_SYMBOL=SMD_DEFAULT_SYMBOL
NETWORK_PORT_TRANSFORMER_SYMBOL=SMD_DEFAULT_SYMBOL
NIOBIUM_OXIDE_CAPACITOR_SYMBOL=SMD_DEFAULT_SYMBOL
NTC_RESISTOR_SYMBOL=SMD_DEFAULT_SYMBOL
OP_AMP_GENERAL_OP_AMP_SYMBOL=SMD_DEFAULT_SYMBOL
OP_AMP_PRECISION_OP_AMP_SYMBOL=SMD_DEFAULT_SYMBOL
OPTICAL_SENSORS_SYMBOL=SMD_DEFAULT_SYMBOL
OPTOCOUPLER_SYMBOL=SMD_DEFAULT_SYMBOL
PASSIVE_CRYSTAL_RESONATOR_SYMBOL=SMD_DEFAULT_SYMBOL
PHOTOELECTRIC_SOLID_STATE_RELAY_SYMBOL=SMD_DEFAULT_SYMBOL
PHOTOELECTRIC_SWITCH_SYMBOL=SMD_DEFAULT_SYMBOL
PHOTOELECTRIC_TRIAC_SYMBOL=SMD_DEFAULT_SYMBOL
PORT_EXPANSION_CHIP_SYMBOL=SMD_DEFAULT_SYMBOL
POSITION_SENSOR_SYMBOL=SMD_DEFAULT_SYMBOL
POWER_INDUCTOR_SYMBOL=SMD_DEFAULT_SYMBOL
POWER_MONITORING_CHIP_SYMBOL=SMD_DEFAULT_SYMBOL
POWER_SWITCH_CHIP_SYMBOL=SMD_DEFAULT_SYMBOL
PRESSURE_SENSOR_SYMBOL=SMD_DEFAULT_SYMBOL
PROFESSIONAL_POWER_MANAGEMENT_PMIC_SYMBOL=SMD_DEFAULT_SYMBOL
PTC_RESETTABLE_FUSE_SYMBOL=SMD_DEFAULT_SYMBOL
REAL_TIME_CLOCK_CHIP_SYMBOL=SMD_DEFAULT_SYMBOL
RECTIFIER_BRIDGE_SYMBOL=SMD_DEFAULT_SYMBOL
RESISTOR_NETWORK_SYMBOL=SMD_DEFAULT_SYMBOL
RESISTOR_SYMBOL=SMD_DEFAULT_SYMBOL
RF_AMPLIFIER_SYMBOL=SMD_DEFAULT_SYMBOL
RF_ATTENUATOR_SYMBOL=SMD_DEFAULT_SYMBOL
RF_CARD_CHIP_SYMBOL=SMD_DEFAULT_SYMBOL
RF_COUPLER_SYMBOL=SMD_DEFAULT_SYMBOL
RF_DETECTOR_SYMBOL=SMD_DEFAULT_SYMBOL
RF_FILTER_SYMBOL=SMD_DEFAULT_SYMBOL
RF_MIXER_SYMBOL=SMD_DEFAULT_SYMBOL
RF_SWITCH_SYMBOL=SMD_DEFAULT_SYMBOL
RS232_CHIP_SYMBOL=SMD_DEFAULT_SYMBOL
RS485_RS422_CHIP_SYMBOL=SMD_DEFAULT_SYMBOL
SCHOTTKY_DIODE_SYMBOL=SMD_DEFAULT_SYMBOL
SDRAM_MEMORY_SYMBOL=SMD_DEFAULT_SYMBOL
SECOND_CLASSIFICATION_OF_ENGINEERING_DEPARTMENT_DATA_SYMBOL=SMD_DEFAULT_SYMBOL
SECURITY_VERIFICATION_ENCRYPTION_CHIP_SYMBOL=SMD_DEFAULT_SYMBOL
SENSOR_INTERFACE_CHIP_SYMBOL=SMD_DEFAULT_SYMBOL
SERIAL_INTERFACE_SYMBOL=SMD_DEFAULT_SYMBOL
SHIFT_REGISTER_SYMBOL=SMD_DEFAULT_SYMBOL
SIGNAL_BUFFERS_REPEATERS_DISTRIBUTORS_SYMBOL=SMD_DEFAULT_SYMBOL
SIGNAL_SWITCHES_MULTIPLEXERS_DECODERS_SYMBOL=SMD_DEFAULT_SYMBOL
ACTIVE_CRYSTAL_OSCILLATOR_SYMBOL=SMD_DEFAULT_SYMBOL
SOLID_ELECTROLYTIC_CAPACITOR_SYMBOL=SMD_DEFAULT_SYMBOL
SOUND_SURFACE_RESONATOR_SAW_SYMBOL=SMD_DEFAULT_SYMBOL
SPECIAL_FUNCTION_AMPLIFIER_SYMBOL=SMD_DEFAULT_SYMBOL
SPECIAL_FUNCTION_DRIVEN_SYMBOL=SMD_DEFAULT_SYMBOL
SRAM_MEMORY_SYMBOL=SMD_DEFAULT_SYMBOL
SWITCHING_DIODE_SYMBOL=SMD_DEFAULT_SYMBOL
SWITCHING_POWER_CHIP_SYMBOL=SMD_DEFAULT_SYMBOL
TACT_SWITCH_SYMBOL=SMD_DEFAULT_SYMBOL
TEMPERATURE_AND_HUMIDITY_SENSOR_SYMBOL=SMD_DEFAULT_SYMBOL
TEMPERATURE_SENSOR_SYMBOL=SMD_DEFAULT_SYMBOL
THYRISTOR_SYMBOL=SMD_DEFAULT_SYMBOL
TIME_BASE_INTEGRATED_CHIP_SYMBOL=SMD_DEFAULT_SYMBOL
TOUCH_CHIP_SYMBOL=SMD_DEFAULT_SYMBOL
TOUCH_SCREEN_CONTROLLER_SYMBOL=SMD_DEFAULT_SYMBOL
TRIGGER_DIODE_SYMBOL=SMD_DEFAULT_SYMBOL
TRIGGER_SYMBOL=SMD_DEFAULT_SYMBOL
TRIODE_DIGITAL_TRIODE_SYMBOL=SMD_DEFAULT_SYMBOL
TRIODE_SYMBOL=SMD_DEFAULT_SYMBOL
TVS_DIODE_SYMBOL=SMD_DEFAULT_SYMBOL
ULTRA_FAST_RECOVERY_DIODE_SYMBOL=SMD_DEFAULT_SYMBOL
USB_CHIP_SYMBOL=SMD_DEFAULT_SYMBOL
VARICAP_DIODE_SYMBOL=SMD_DEFAULT_SYMBOL
VARISTOR_SYMBOL=SMD_DEFAULT_SYMBOL
VIDEO_AND_AUDIO_INTERFACE_CHIP_SYMBOL=SMD_DEFAULT_SYMBOL
VIDEO_FILTER_DRIVER_SYMBOL=SMD_DEFAULT_SYMBOL
VOLTAGE_COMPARATOR_SYMBOL=SMD_DEFAULT_SYMBOL
VOLTAGE_REFERENCE_CHIP_SYMBOL=SMD_DEFAULT_SYMBOL
WIRELESS_TRANSCEIVER_CHIP_SYMBOL=SMD_DEFAULT_SYMBOL
MICROCONTROLLER_MCU_SYMBOL=SMD_DEFAULT_SYMBOL


def lookup_drawing(component_category_in):
  return component_drawing[component_category_in]
