#!/usr/bin/env python3
import os,sys,re
from constant import *


SMD_CAPACITOR_SYMBOL='''
P 2 0 1 13 -60 -20 60 -20 N
P 2 0 1 12 -60 20 60 20 N
X ~ 1 0 100 80 D 50 50 1 1 P
X ~ 2 0 -100 80 U 50 50 1 1 P
'''.strip()

SMD_RESISTOR_SYMBOL='''
S -30 70 30 -70 0 1 8 N
X ~ 1 0 100 30 D 50 50 1 1 P
X ~ 2 0 -100 30 U 50 50 1 1 P
'''.strip()

SMD_INDUCTOR_SYMBOL='''
A 0 -60 20 -899 899 0 1 0 N 0 -80 0 -40
A 0 -20 20 -899 899 0 1 0 N 0 -40 0 0
A 0 20 20 -899 899 0 1 0 N 0 0 0 40
A 0 60 20 -899 899 0 1 0 N 0 40 0 80
X ~ 1 0 100 20 D 50 50 1 1 P
X ~ 2 0 -100 20 U 50 50 1 1 P
'''.strip()

SMD_LED_SYMBOL='''
P 2 0 1 0 -30 -40 -30 40 N
P 2 0 1 0 40 0 -30 0 N
P 4 0 1 0 30 -40 -30 0 30 40 30 -40 N
P 5 0 1 0 0 30 -20 50 -10 50 -20 50 -20 40 N
P 5 0 1 0 20 50 0 70 10 70 0 70 0 60 N
X K 1 -100 0 70 R 50 50 1 1 P
X A 2 100 0 70 L 50 50 1 1 P
'''.strip()

SMD_DIODE_SYMBOL='''
P 2 0 1 0 -30 -40 -30 40 N
P 2 0 1 0 -30 0 30 0 N
P 4 0 1 0 30 -40 -30 0 30 40 30 -40 N
X K 1 -100 0 70 R 50 50 1 1 P
X A 2 100 0 70 L 50 50 1 1 P
'''.strip()



component_drawing = {
  CAT_SMD_CAPACITOR: SMD_CAPACITOR_SYMBOL,
  CAT_SMD_RESISTOR: SMD_RESISTOR_SYMBOL,
  CAT_SMD_INDUCTOR: SMD_INDUCTOR_SYMBOL,
  CAT_SMD_LED: SMD_LED_SYMBOL,
  CAT_SMD_DIODE: SMD_DIODE_SYMBOL,

  # CAT_SMD_ACTIVE_FILTER: SMD_DIODE_SYMBOL
  # CAT_SMD_AMBIENT_LIGHT_SENSOR: SMD_DIODE_SYMBOL
  # CAT_SMD_AMPLIFIER: SMD_DIODE_SYMBOL
  # CAT_SMD_ANALOG_SWITCH_CHIP: SMD_DIODE_SYMBOL
  # CAT_SMD_ANALOG_TO_DIGITAL_CONVERSION_CHIP: SMD_DIODE_SYMBOL
  # CAT_SMD_ANGLE_SENSOR: SMD_DIODE_SYMBOL
  # CAT_SMD_ANGULAR_VELOCITY_SENSOR: SMD_DIODE_SYMBOL
  # CAT_SMD_ATTITUDE_SENSOR: SMD_DIODE_SYMBOL
  # CAT_SMD_AUDIO_POWER_AMPLIFIER: SMD_DIODE_SYMBOL
  # CAT_SMD_AVALANCHE_DIODE: SMD_DIODE_SYMBOL
  # CAT_SMD_BALANCED_UNBALANCED_TRANSFORMER: SMD_DIODE_SYMBOL
  # CAT_SMD_BALLAST_CONTROLLER: SMD_DIODE_SYMBOL
  # CAT_SMD_BATTERY_BOX_BATTERY_HOLDER: SMD_DIODE_SYMBOL
  # CAT_SMD_BATTERY_POWER_MANAGEMENT_CHIP: SMD_DIODE_SYMBOL
  # CAT_SMD_BATTERY_PROTECTION_CHIP: SMD_DIODE_SYMBOL
  # CAT_SMD_BUFFERS_DRIVERS_RECEIVERS_TRANSCEIVERS: SMD_DIODE_SYMBOL
  # CAT_SMD_CAN_CHIP: SMD_DIODE_SYMBOL
  # CAT_SMD_CAPACITOR: SMD_DIODE_SYMBOL
  # CAT_SMD_CERAMIC_RESONATOR: SMD_DIODE_SYMBOL
  # CAT_SMD_CLOCK_BUFFER_DRIVER: SMD_DIODE_SYMBOL
  # CAT_SMD_CLOCK_GENERATOR_PLL_FREQUENCY_SYNTHESIZER: SMD_DIODE_SYMBOL
  # CAT_SMD_CLOCK_TIMING_DEDICATED: SMD_DIODE_SYMBOL
  # CAT_SMD_CODEC_CHIP: SMD_DIODE_SYMBOL
  # CAT_SMD_COLOR_SENSOR: SMD_DIODE_SYMBOL
  # CAT_SMD_COMMON_MODE_INDUCTOR_FILTER: SMD_DIODE_SYMBOL
  # CAT_SMD_CONSTANT_CURRENT_DIODE: SMD_DIODE_SYMBOL
  # CAT_SMD_CONSTANT_CURRENT_DIODE: SMD_DIODE_SYMBOL
  # CAT_SMD_COUNTER_DIVIDER: SMD_DIODE_SYMBOL
  # CAT_SMD_CPLD_FPGA_CHIP: SMD_DIODE_SYMBOL
  # CAT_SMD_CURRENT_MONITORING_CHIP: SMD_DIODE_SYMBOL
  # CAT_SMD_CURRENT_SENSOR: SMD_DIODE_SYMBOL
  # CAT_SMD_DARLINGTON_TRANSISTOR_ARRAY_DRIVE: SMD_DIODE_SYMBOL
  # CAT_SMD_DARLINGTON: SMD_DIODE_SYMBOL
  # CAT_SMD_DC_DC_CHIP: SMD_DIODE_SYMBOL
  # CAT_SMD_DDR_MEMORY: SMD_DIODE_SYMBOL
  # CAT_SMD_DDS_CHIP: SMD_DIODE_SYMBOL
  # CAT_SMD_DEDICATED_SENSORS: SMD_DIODE_SYMBOL
  # CAT_SMD_DIFFERENTIAL_OP_AMPS: SMD_DIODE_SYMBOL
  # CAT_SMD_DIGITAL_POTENTIOMETER_CHIP: SMD_DIODE_SYMBOL
  # CAT_SMD_DIGITAL_TO_ANALOG_CONVERSION_CHIP: SMD_DIODE_SYMBOL
  # CAT_SMD_DIODE: SMD_DIODE_SYMBOL
  # CAT_SMD_DISCHARGE_TUBE: SMD_DIODE_SYMBOL
  # CAT_SMD_DRIVER_CHIP: SMD_DIODE_SYMBOL
  # CAT_SMD_EEPROM_MEMORY: SMD_DIODE_SYMBOL
  # CAT_SMD_EL_DRIVE: SMD_DIODE_SYMBOL
  # CAT_SMD_ELECTROLYTIC_CAPACITORS: SMD_DIODE_SYMBOL
  # CAT_SMD_EMI_RFI_FILTERS_LC_RC_NETWORKS: SMD_DIODE_SYMBOL
  # CAT_SMD_EPROM_MEMORY: SMD_DIODE_SYMBOL
  CAT_SMD_ESD_DIODE: SMD_DIODE_SYMBOL,
  # CAT_SMD_ETHERNET_CHIP: SMD_DIODE_SYMBOL
  # CAT_SMD_FAST_RECOVERY_DIODE: SMD_DIODE_SYMBOL
  # CAT_SMD_FAST_RECOVERY_DIODE: SMD_DIODE_SYMBOL
  # CAT_SMD_FET_INPUT_OP_AMP: SMD_DIODE_SYMBOL
  # CAT_SMD_FLASH_MEMORY: SMD_DIODE_SYMBOL
  # CAT_SMD_FONT_CHIP: SMD_DIODE_SYMBOL
  # CAT_SMD_FRAM_MEMORY: SMD_DIODE_SYMBOL
  # CAT_SMD_FUEL_GAUGE_CHIP: SMD_DIODE_SYMBOL
  # CAT_SMD_FULL_BRIDGE_HALF_BRIDGE_DRIVE: SMD_DIODE_SYMBOL
  # CAT_SMD_GAS_SENSOR: SMD_DIODE_SYMBOL
  # CAT_SMD_GATE_AND_INVERTER: SMD_DIODE_SYMBOL
  # CAT_SMD_HF_INDUCTOR: SMD_DIODE_SYMBOL
  # CAT_SMD_HIGH_EFFICIENCY_DIODE: SMD_DIODE_SYMBOL
  # CAT_SMD_HIGH_PRESISION_RESISTOR: SMD_DIODE_SYMBOL
  # CAT_SMD_HIGH_SPEED_BROADBAND_OP_AMP: SMD_DIODE_SYMBOL
  # CAT_SMD_HIGH_VOLTAGE_RESISTOR: SMD_DIODE_SYMBOL
  # CAT_SMD_I_O_EXPANDER: SMD_DIODE_SYMBOL
  # CAT_SMD_IGBT_DRIVE: SMD_DIODE_SYMBOL
  # CAT_SMD_IGBT_TUBE: SMD_DIODE_SYMBOL
  # CAT_SMD_INDUCTOR: SMD_DIODE_SYMBOL
  # CAT_SMD_INFRARED_EMISSION_TUBE: SMD_DIODE_SYMBOL
  # CAT_SMD_INFRARED_RECEIVER_TUBE: SMD_DIODE_SYMBOL
  # CAT_SMD_INFRARED_SENSOR: SMD_DIODE_SYMBOL
  # CAT_SMD_INSTRUMENT_OPERATIONAL_AMPLIFIER: SMD_DIODE_SYMBOL
  # CAT_SMD_INTERFACE_CHIP: SMD_DIODE_SYMBOL
  # CAT_SMD_INTERFACE_CONTROLLER: SMD_DIODE_SYMBOL
  # CAT_SMD_INTERFACE_DEDICATED: SMD_DIODE_SYMBOL
  # CAT_SMD_INTERFACE_LIN_TRANSCEIVER: SMD_DIODE_SYMBOL
  # CAT_SMD_INTERFACE_TELECOM: SMD_DIODE_SYMBOL
  # CAT_SMD_ISOLATOR_CHIP: SMD_DIODE_SYMBOL
  # CAT_SMD_JFET_JUNCTION_FIELD_EFFECT_TRANSISTOR: SMD_DIODE_SYMBOL
  # CAT_SMD_LATCHES: SMD_DIODE_SYMBOL
  # CAT_SMD_LCD_DRIVER: SMD_DIODE_SYMBOL
  # CAT_SMD_LDO_LOW_DROPOUT_LINEAR_REGULATION: SMD_DIODE_SYMBOL
  # CAT_SMD_LED_DRIVE: SMD_DIODE_SYMBOL
  # CAT_SMD_LED_RESISTOR: SMD_DIODE_SYMBOL
  # CAT_SMD_LED: SMD_DIODE_SYMBOL
  # CAT_SMD_LEVEL_SHIFTER_SHIFTER: SMD_DIODE_SYMBOL
  # CAT_SMD_LINEAR_VOLTAGE_REGULATOR_CHIP: SMD_DIODE_SYMBOL
  # CAT_SMD_LOGIC_CHIP_: SMD_DIODE_SYMBOL
  # CAT_SMD_LOGIC_CHIP_4000_SERIES: SMD_DIODE_SYMBOL
  # CAT_SMD_LOGIC_CHIP_74_SERIES: SMD_DIODE_SYMBOL
  # CAT_SMD_LOW_NOISE_OP_AMP: SMD_DIODE_SYMBOL
  # CAT_SMD_LOW_POWER_OP_AMP: SMD_DIODE_SYMBOL
  # CAT_SMD_LVDS_CHIP: SMD_DIODE_SYMBOL
  # CAT_SMD_MAGNETIC_SENSOR: SMD_DIODE_SYMBOL
  # CAT_SMD_MCU_MONITORING_CHIP: SMD_DIODE_SYMBOL
  # CAT_SMD_MICROCONTROLLER_MCU: SMD_DIODE_SYMBOL
  # CAT_SMD_MOS_DRIVE: SMD_DIODE_SYMBOL
  # CAT_SMD_MOS_FIELD_EFFECT_TUBE: SMD_DIODE_SYMBOL
  # CAT_SMD_MOTOR_DRIVER: SMD_DIODE_SYMBOL
  # CAT_SMD_MULTI_FREQUENCY_OSCILLATOR: SMD_DIODE_SYMBOL
  # CAT_SMD_NETWORK_PORT_TRANSFORMER: SMD_DIODE_SYMBOL
  # CAT_SMD_NIOBIUM_OXIDE_CAPACITOR: SMD_DIODE_SYMBOL
  # CAT_SMD_NTC_RESISTOR: SMD_DIODE_SYMBOL
  # CAT_SMD_OP_AMP_GENERAL_OP_AMP: SMD_DIODE_SYMBOL
  # CAT_SMD_OP_AMP_PRECISION_OP_AMP: SMD_DIODE_SYMBOL
  # CAT_SMD_OPTICAL_SENSORS: SMD_DIODE_SYMBOL
  # CAT_SMD_PHOTOELECTRIC_SOLID_STATE_RELAY: SMD_DIODE_SYMBOL
  # CAT_SMD_PHOTOELECTRIC_SWITCH: SMD_DIODE_SYMBOL
  # CAT_SMD_PHOTOELECTRIC_TRIAC: SMD_DIODE_SYMBOL
  # CAT_SMD_PORT_EXPANSION_CHIP: SMD_DIODE_SYMBOL
  # CAT_SMD_POSITION_SENSOR: SMD_DIODE_SYMBOL
  # CAT_SMD_POWER_INDUCTOR: SMD_DIODE_SYMBOL
  # CAT_SMD_POWER_MONITORING_CHIP: SMD_DIODE_SYMBOL
  # CAT_SMD_POWER_SWITCH_CHIP: SMD_DIODE_SYMBOL
  # CAT_SMD_PRESSURE_SENSOR: SMD_DIODE_SYMBOL
  # CAT_SMD_PROFESSIONAL_POWER_MANAGEMENT_PMIC: SMD_DIODE_SYMBOL
  # CAT_SMD_PTC_RESETTABLE_FUSE: SMD_DIODE_SYMBOL
  # CAT_SMD_REAL_TIME_CLOCK_CHIP: SMD_DIODE_SYMBOL
  # CAT_SMD_RECTIFIER_BRIDGE: SMD_DIODE_SYMBOL
  # CAT_SMD_RESISTOR_NETWORK: SMD_DIODE_SYMBOL
  # CAT_SMD_RESISTOR: SMD_DIODE_SYMBOL
  # CAT_SMD_RF_AMPLIFIER: SMD_DIODE_SYMBOL
  # CAT_SMD_RF_ATTENUATOR: SMD_DIODE_SYMBOL
  # CAT_SMD_RF_CARD_CHIP: SMD_DIODE_SYMBOL
  # CAT_SMD_RF_COUPLER: SMD_DIODE_SYMBOL
  # CAT_SMD_RF_DETECTOR: SMD_DIODE_SYMBOL
  # CAT_SMD_RF_FILTER: SMD_DIODE_SYMBOL
  # CAT_SMD_RF_MIXER: SMD_DIODE_SYMBOL
  # CAT_SMD_RF_SWITCH: SMD_DIODE_SYMBOL
  # CAT_SMD_RS232_CHIP: SMD_DIODE_SYMBOL
  # CAT_SMD_RS485_RS422_CHIP: SMD_DIODE_SYMBOL
  # CAT_SMD_SCHOTTKY_DIODE: SMD_DIODE_SYMBOL
  # CAT_SMD_SDRAM_MEMORY: SMD_DIODE_SYMBOL
  # CAT_SMD_SECOND_CLASSIFICATION_OF_ENGINEERING_DEPARTMENT_DATA: SMD_DIODE_SYMBOL
  # CAT_SMD_SECURITY_VERIFICATION_ENCRYPTION_CHIP: SMD_DIODE_SYMBOL
  # CAT_SMD_SENSOR_INTERFACE_CHIP: SMD_DIODE_SYMBOL
  # CAT_SMD_SERIAL_INTERFACE: SMD_DIODE_SYMBOL
  # CAT_SMD_SHIFT_REGISTER: SMD_DIODE_SYMBOL
  # CAT_SMD_SIGNAL_BUFFERS_REPEATERS_DISTRIBUTORS: SMD_DIODE_SYMBOL
  # CAT_SMD_SIGNAL_SWITCHES_MULTIPLEXERS_DECODERS: SMD_DIODE_SYMBOL
  # CAT_SMD_SMD_ACTIVE_CRYSTAL_OSCILLATOR: SMD_DIODE_SYMBOL
  # CAT_SMD_DISPOSABLE_FUSES: SMD_DIODE_SYMBOL
  # CAT_SMD_MAGNETIC_BEADS: SMD_DIODE_SYMBOL
  # CAT_SMD_OPTOCOUPLER: SMD_DIODE_SYMBOL
  # CAT_SMD_PASSIVE_CRYSTAL_RESONATOR: SMD_DIODE_SYMBOL
  # CAT_SMD_SOLID_ELECTROLYTIC_CAPACITOR: SMD_DIODE_SYMBOL
  # CAT_SMD_SOUND_SURFACE_RESONATOR_SAW: SMD_DIODE_SYMBOL
  # CAT_SMD_SPECIAL_FUNCTION_AMPLIFIER: SMD_DIODE_SYMBOL
  # CAT_SMD_SPECIAL_FUNCTION_DRIVEN: SMD_DIODE_SYMBOL
  # CAT_SMD_SRAM_MEMORY: SMD_DIODE_SYMBOL
  # CAT_SMD_SWITCHING_DIODE: SMD_DIODE_SYMBOL
  # CAT_SMD_SWITCHING_POWER_CHIP: SMD_DIODE_SYMBOL
  # CAT_SMD_TACT_SWITCH: SMD_DIODE_SYMBOL
  # CAT_SMD_TANTALUM_CAPACITOR: SMD_DIODE_SYMBOL
  # CAT_SMD_TEMPERATURE_AND_HUMIDITY_SENSOR: SMD_DIODE_SYMBOL
  # CAT_SMD_TEMPERATURE_SENSOR: SMD_DIODE_SYMBOL
  # CAT_SMD_THYRISTOR: SMD_DIODE_SYMBOL
  # CAT_SMD_TIME_BASE_INTEGRATED_CHIP: SMD_DIODE_SYMBOL
  # CAT_SMD_TOUCH_CHIP: SMD_DIODE_SYMBOL
  # CAT_SMD_TOUCH_SCREEN_CONTROLLER: SMD_DIODE_SYMBOL
  # CAT_SMD_TRIGGER_DIODE: SMD_DIODE_SYMBOL
  # CAT_SMD_TRIGGER: SMD_DIODE_SYMBOL
  # CAT_SMD_TRIODE_DIGITAL_TRIODE: SMD_DIODE_SYMBOL
  # CAT_SMD_TRIODE: SMD_DIODE_SYMBOL
  # CAT_SMD_TVS_DIODE: SMD_DIODE_SYMBOL
  # CAT_SMD_ULTRA_FAST_RECOVERY_DIODE: SMD_DIODE_SYMBOL
  # CAT_SMD_USB_CHIP: SMD_DIODE_SYMBOL
  # CAT_SMD_VARICAP_DIODE: SMD_DIODE_SYMBOL
  # CAT_SMD_VARISTOR: SMD_DIODE_SYMBOL
  # CAT_SMD_VIDEO_AND_AUDIO_INTERFACE_CHIP: SMD_DIODE_SYMBOL
  # CAT_SMD_VIDEO_FILTER_DRIVER: SMD_DIODE_SYMBOL
  # CAT_SMD_VOLTAGE_COMPARATOR: SMD_DIODE_SYMBOL
  # CAT_SMD_VOLTAGE_REFERENCE_CHIP: SMD_DIODE_SYMBOL
  # CAT_SMD_WIRELESS_TRANSCEIVER_CHIP: SMD_DIODE_SYMBOL
  # CAT_SMD_ZENER_DIODE: SMD_DIODE_SYMBOL
}

def lookup_drawing(component_category_in):
  return component_drawing[component_category_in]
