#!/usr/bin/env python3

import os,sys,re
from pprint import pprint

from footprint import *
from draw_symbol import *

master_table = [

  [CAT_SMD_CAPACITOR, 'output/sz_jlc_capacitor.lib', 'output/sz_jlc_capacitor.dcm', capacitor_footprint_expand, capacitor_footprint_list_expand, SMD_CAPACITOR_SYMBOL],

  [CAT_SMD_DIODE, 'output/sz_jlc_diode.lib', 'output/sz_jlc_diode.dcm', diode_footprint_expand, diode_footprint_list_expand, SMD_DIODE_SYMBOL],
  [CAT_SMD_ESD_DIODE,  'output/sz_jlc_esd_diode.lib', 'output/sz_jlc_esd_diode.dcm', diode_footprint_expand, diode_footprint_list_expand, SMD_DIODE_SYMBOL],
  [CAT_SMD_ZENER_DIODE,  'output/sz_jlc_zener_diode.lib', 'output/sz_jlc_zener_diode.dcm', diode_footprint_expand, diode_footprint_list_expand, SMD_DIODE_SYMBOL],
  [CAT_SMD_AVALANCHE_DIODE,  'output/sz_jlc_avalanche_diode.lib', 'output/sz_jlc_avalanche_diode.dcm', diode_footprint_expand, diode_footprint_list_expand, SMD_DIODE_SYMBOL],
  [CAT_SMD_LED, 'output/sz_jlc_led.lib', 'output/sz_jlc_led.dcm', diode_footprint_expand, diode_footprint_list_expand, SMD_DIODE_SYMBOL],

  [CAT_SMD_INDUCTOR, 'output/sz_jlc_inductor.lib', 'output/sz_jlc_inductor.dcm', inductor_footprint_expand, inductor_footprint_list_expand, SMD_INDUCTOR_SYMBOL],
  [CAT_SMD_RESISTOR, 'output/sz_jlc_resistor.lib', 'output/sz_jlc_resistor.dcm', resistor_footprint_expand, resistor_footprint_list_expand, SMD_RESISTOR_SYMBOL],
  [CAT_SMD_LDO_LOW_DROPOUT_LINEAR_REGULATION,  'output/sz_jlc_ldo_low_dropout_linear_regulation.lib', 'output/sz_jlc_ldo_low_dropout_linear_regulation.dcm', ldo_low_dropout_linear_regulation_footprint_expand, ldo_low_dropout_linear_regulation_footprint_list_expand, SMD_LDO_SYMBOL],

  # MCU
  # [CAT_SMD_MCU_MONITORING_CHIP,  'output/sz_jlc_mcu_monitoring_chip.lib', 'output/sz_jlc_mcu_monitoring_chip.dcm'],
  [CAT_SMD_MICROCONTROLLER_MCU,  'output/sz_jlc_microcontroller_mcu.lib', 'output/sz_jlc_microcontroller_mcu.dcm', microcontroller_mcu_footprint_expand, microcontroller_mcu_footprint_list_expand, SMD_MICROCONTROLLER_MCU_SYMBOL],

  # [CAT_SMD_ACCELEROMETER,  'output/sz_jlc_accelerometer.lib', 'output/sz_jlc_accelerometer.dcm'],
  # [CAT_SMD_ACTIVE_FILTER,  'output/sz_jlc_active_filter.lib', 'output/sz_jlc_active_filter.dcm'],
  # [CAT_SMD_AMBIENT_LIGHT_SENSOR,  'output/sz_jlc_ambient_light_sensor.lib', 'output/sz_jlc_ambient_light_sensor.dcm'],
  # [CAT_SMD_AMPLIFIER,  'output/sz_jlc_amplifier.lib', 'output/sz_jlc_amplifier.dcm'],
  # [CAT_SMD_ANALOG_SWITCH_CHIP,  'output/sz_jlc_analog_switch_chip.lib', 'output/sz_jlc_analog_switch_chip.dcm'],
  # [CAT_SMD_ANALOG_TO_DIGITAL_CONVERSION_CHIP,  'output/sz_jlc_analog_to_digital_conversion_chip.lib', 'output/sz_jlc_analog_to_digital_conversion_chip.dcm'],
  # [CAT_SMD_ANGLE_SENSOR,  'output/sz_jlc_angle_sensor.lib', 'output/sz_jlc_angle_sensor.dcm'],
  # [CAT_SMD_ANGULAR_VELOCITY_SENSOR,  'output/sz_jlc_angular_velocity_sensor.lib', 'output/sz_jlc_angular_velocity_sensor.dcm'],
  # [CAT_SMD_ATTITUDE_SENSOR,  'output/sz_jlc_attitude_sensor.lib', 'output/sz_jlc_attitude_sensor.dcm'],
  # [CAT_SMD_AUDIO_POWER_AMPLIFIER,  'output/sz_jlc_audio_power_amplifier.lib', 'output/sz_jlc_audio_power_amplifier.dcm'],

  # [CAT_SMD_BALANCED_UNBALANCED_TRANSFORMER,  'output/sz_jlc_balanced_unbalanced_transformer.lib', 'output/sz_jlc_balanced_unbalanced_transformer.dcm'],
  # [CAT_SMD_BALLAST_CONTROLLER,  'output/sz_jlc_ballast_controller.lib', 'output/sz_jlc_ballast_controller.dcm'],
  # [CAT_SMD_BATTERY_BOX_BATTERY_HOLDER,  'output/sz_jlc_battery_box_battery_holder.lib', 'output/sz_jlc_battery_box_battery_holder.dcm'],
  # [CAT_SMD_BATTERY_POWER_MANAGEMENT_CHIP,  'output/sz_jlc_battery_power_management_chip.lib', 'output/sz_jlc_battery_power_management_chip.dcm'],
  # [CAT_SMD_BATTERY_PROTECTION_CHIP,  'output/sz_jlc_battery_protection_chip.lib', 'output/sz_jlc_battery_protection_chip.dcm'],
  # [CAT_SMD_BUFFERS_DRIVERS_RECEIVERS_TRANSCEIVERS,  'output/sz_jlc_buffers_drivers_receivers_transceivers.lib', 'output/sz_jlc_buffers_drivers_receivers_transceivers.dcm'],
  # [CAT_SMD_CAN_CHIP,  'output/sz_jlc_can_chip.lib', 'output/sz_jlc_can_chip.dcm'],
  # [CAT_SMD_CERAMIC_RESONATOR,  'output/sz_jlc_ceramic_resonator.lib', 'output/sz_jlc_ceramic_resonator.dcm'],
  # [CAT_SMD_CLOCK_BUFFER_DRIVER,  'output/sz_jlc_clock_buffer_driver.lib', 'output/sz_jlc_clock_buffer_driver.dcm'],
  # [CAT_SMD_CLOCK_GENERATOR_PLL_FREQUENCY_SYNTHESIZER,  'output/sz_jlc_clock_generator_pll_frequency_synthesizer.lib', 'output/sz_jlc_clock_generator_pll_frequency_synthesizer.dcm'],
  # [CAT_SMD_CLOCK_TIMING_DEDICATED,  'output/sz_jlc_clock_timing_dedicated.lib', 'output/sz_jlc_clock_timing_dedicated.dcm'],
  # [CAT_SMD_CODEC_CHIP,  'output/sz_jlc_codec_chip.lib', 'output/sz_jlc_codec_chip.dcm'],
  # [CAT_SMD_COLOR_SENSOR,  'output/sz_jlc_color_sensor.lib', 'output/sz_jlc_color_sensor.dcm'],
  # [CAT_SMD_COMMON_MODE_INDUCTOR_FILTER,  'output/sz_jlc_common_mode_inductor_filter.lib', 'output/sz_jlc_common_mode_inductor_filter.dcm'],
  # [CAT_SMD_CONSTANT_CURRENT_DIODE,  'output/sz_jlc_constant_current_diode.lib', 'output/sz_jlc_constant_current_diode.dcm'],
  # [CAT_SMD_CONSTANT_CURRENT_DIODE,  'output/sz_jlc_constant_current_diode.lib', 'output/sz_jlc_constant_current_diode.dcm'],
  # [CAT_SMD_COUNTER_DIVIDER,  'output/sz_jlc_counter_divider.lib', 'output/sz_jlc_counter_divider.dcm'],
  # [CAT_SMD_CPLD_FPGA_CHIP,  'output/sz_jlc_cpld_fpga_chip.lib', 'output/sz_jlc_cpld_fpga_chip.dcm'],
  # [CAT_SMD_CURRENT_MONITORING_CHIP,  'output/sz_jlc_current_monitoring_chip.lib', 'output/sz_jlc_current_monitoring_chip.dcm'],
  # [CAT_SMD_CURRENT_SENSOR,  'output/sz_jlc_current_sensor.lib', 'output/sz_jlc_current_sensor.dcm'],
  # [CAT_SMD_DARLINGTON_TRANSISTOR_ARRAY_DRIVE,  'output/sz_jlc_darlington_transistor_array_drive.lib', 'output/sz_jlc_darlington_transistor_array_drive.dcm'],
  # [CAT_SMD_DARLINGTON,  'output/sz_jlc_darlington.lib', 'output/sz_jlc_darlington.dcm'],
  # [CAT_SMD_DC_DC_CHIP,  'output/sz_jlc_dc_dc_chip.lib', 'output/sz_jlc_dc_dc_chip.dcm'],
  # [CAT_SMD_DDR_MEMORY,  'output/sz_jlc_ddr_memory.lib', 'output/sz_jlc_ddr_memory.dcm'],
  # [CAT_SMD_DDS_CHIP,  'output/sz_jlc_dds_chip.lib', 'output/sz_jlc_dds_chip.dcm'],
  # [CAT_SMD_DEDICATED_SENSORS,  'output/sz_jlc_dedicated_sensors.lib', 'output/sz_jlc_dedicated_sensors.dcm'],
  # [CAT_SMD_DIFFERENTIAL_OP_AMPS,  'output/sz_jlc_differential_op_amps.lib', 'output/sz_jlc_differential_op_amps.dcm'],
  # [CAT_SMD_DIGITAL_POTENTIOMETER_CHIP,  'output/sz_jlc_digital_potentiometer_chip.lib', 'output/sz_jlc_digital_potentiometer_chip.dcm'],
  # [CAT_SMD_DIGITAL_TO_ANALOG_CONVERSION_CHIP,  'output/sz_jlc_digital_to_analog_conversion_chip.lib', 'output/sz_jlc_digital_to_analog_conversion_chip.dcm'],
  # [CAT_SMD_DISCHARGE_TUBE,  'output/sz_jlc_discharge_tube.lib', 'output/sz_jlc_discharge_tube.dcm'],
  # [CAT_SMD_DISPOSABLE_FUSES,  'output/sz_jlc_disposable_fuses.lib', 'output/sz_jlc_disposable_fuses.dcm'],
  # [CAT_SMD_DRIVER_CHIP,  'output/sz_jlc_driver_chip.lib', 'output/sz_jlc_driver_chip.dcm'],
  # [CAT_SMD_EEPROM_MEMORY,  'output/sz_jlc_eeprom_memory.lib', 'output/sz_jlc_eeprom_memory.dcm'],
  # [CAT_SMD_EL_DRIVE,  'output/sz_jlc_el_drive.lib', 'output/sz_jlc_el_drive.dcm'],
  # [CAT_SMD_ELECTROLYTIC_CAPACITORS,  'output/sz_jlc_electrolytic_capacitors.lib', 'output/sz_jlc_electrolytic_capacitors.dcm'],
  # [CAT_SMD_EMI_RFI_FILTERS_LC_RC_NETWORKS,  'output/sz_jlc_emi_rfi_filters_lc_rc_networks.lib', 'output/sz_jlc_emi_rfi_filters_lc_rc_networks.dcm'],
  # [CAT_SMD_EPROM_MEMORY,  'output/sz_jlc_eprom_memory.lib', 'output/sz_jlc_eprom_memory.dcm'],
  # [CAT_SMD_ETHERNET_CHIP,  'output/sz_jlc_ethernet_chip.lib', 'output/sz_jlc_ethernet_chip.dcm'],
  # [CAT_SMD_FAST_RECOVERY_DIODE,  'output/sz_jlc_fast_recovery_diode.lib', 'output/sz_jlc_fast_recovery_diode.dcm'],
  # [CAT_SMD_FAST_RECOVERY_DIODE,  'output/sz_jlc_fast_recovery_diode.lib', 'output/sz_jlc_fast_recovery_diode.dcm'],
  # [CAT_SMD_FET_INPUT_OP_AMP,  'output/sz_jlc_fet_input_op_amp.lib', 'output/sz_jlc_fet_input_op_amp.dcm'],
  # [CAT_SMD_FLASH_MEMORY,  'output/sz_jlc_flash_memory.lib', 'output/sz_jlc_flash_memory.dcm'],
  # [CAT_SMD_FONT_CHIP,  'output/sz_jlc_font_chip.lib', 'output/sz_jlc_font_chip.dcm'],
  # [CAT_SMD_FRAM_MEMORY,  'output/sz_jlc_fram_memory.lib', 'output/sz_jlc_fram_memory.dcm'],
  # [CAT_SMD_FUEL_GAUGE_CHIP,  'output/sz_jlc_fuel_gauge_chip.lib', 'output/sz_jlc_fuel_gauge_chip.dcm'],
  # [CAT_SMD_FULL_BRIDGE_HALF_BRIDGE_DRIVE,  'output/sz_jlc_full_bridge_half_bridge_drive.lib', 'output/sz_jlc_full_bridge_half_bridge_drive.dcm'],
  # [CAT_SMD_GAS_SENSOR,  'output/sz_jlc_gas_sensor.lib', 'output/sz_jlc_gas_sensor.dcm'],
  # [CAT_SMD_GATE_AND_INVERTER,  'output/sz_jlc_gate_and_inverter.lib', 'output/sz_jlc_gate_and_inverter.dcm'],
  # [CAT_SMD_HF_INDUCTOR,  'output/sz_jlc_hf_inductor.lib', 'output/sz_jlc_hf_inductor.dcm'],
  # [CAT_SMD_HIGH_EFFICIENCY_DIODE,  'output/sz_jlc_high_efficiency_diode.lib', 'output/sz_jlc_high_efficiency_diode.dcm'],
  # [CAT_SMD_HIGH_PRESISION_RESISTOR,  'output/sz_jlc_high_presision_resistor.lib', 'output/sz_jlc_high_presision_resistor.dcm'],
  # [CAT_SMD_HIGH_SPEED_BROADBAND_OP_AMP,  'output/sz_jlc_high_speed_broadband_op_amp.lib', 'output/sz_jlc_high_speed_broadband_op_amp.dcm'],
  # [CAT_SMD_HIGH_VOLTAGE_RESISTOR,  'output/sz_jlc_high_voltage_resistor.lib', 'output/sz_jlc_high_voltage_resistor.dcm'],
  # [CAT_SMD_I_O_EXPANDER,  'output/sz_jlc_i_o_expander.lib', 'output/sz_jlc_i_o_expander.dcm'],
  # [CAT_SMD_IGBT_DRIVE,  'output/sz_jlc_igbt_drive.lib', 'output/sz_jlc_igbt_drive.dcm'],
  # [CAT_SMD_IGBT_TUBE,  'output/sz_jlc_igbt_tube.lib', 'output/sz_jlc_igbt_tube.dcm'],
  # [CAT_SMD_INFRARED_EMISSION_TUBE,  'output/sz_jlc_infrared_emission_tube.lib', 'output/sz_jlc_infrared_emission_tube.dcm'],
  # [CAT_SMD_INFRARED_RECEIVER_TUBE,  'output/sz_jlc_infrared_receiver_tube.lib', 'output/sz_jlc_infrared_receiver_tube.dcm'],
  # [CAT_SMD_INFRARED_SENSOR,  'output/sz_jlc_infrared_sensor.lib', 'output/sz_jlc_infrared_sensor.dcm'],
  # [CAT_SMD_INSTRUMENT_OPERATIONAL_AMPLIFIER,  'output/sz_jlc_instrument_operational_amplifier.lib', 'output/sz_jlc_instrument_operational_amplifier.dcm'],
  # [CAT_SMD_INTERFACE_CHIP,  'output/sz_jlc_interface_chip.lib', 'output/sz_jlc_interface_chip.dcm'],
  # [CAT_SMD_INTERFACE_CONTROLLER,  'output/sz_jlc_interface_controller.lib', 'output/sz_jlc_interface_controller.dcm'],
  # [CAT_SMD_INTERFACE_DEDICATED,  'output/sz_jlc_interface_dedicated.lib', 'output/sz_jlc_interface_dedicated.dcm'],
  # [CAT_SMD_INTERFACE_LIN_TRANSCEIVER,  'output/sz_jlc_interface_lin_transceiver.lib', 'output/sz_jlc_interface_lin_transceiver.dcm'],
  # [CAT_SMD_INTERFACE_TELECOM,  'output/sz_jlc_interface_telecom.lib', 'output/sz_jlc_interface_telecom.dcm'],
  # [CAT_SMD_ISOLATOR_CHIP,  'output/sz_jlc_isolator_chip.lib', 'output/sz_jlc_isolator_chip.dcm'],
  # [CAT_SMD_JFET_JUNCTION_FIELD_EFFECT_TRANSISTOR,  'output/sz_jlc_jfet_junction_field_effect_transistor.lib', 'output/sz_jlc_jfet_junction_field_effect_transistor.dcm'],
  # [CAT_SMD_LATCHES,  'output/sz_jlc_latches.lib', 'output/sz_jlc_latches.dcm'],
  # [CAT_SMD_LCD_DRIVER,  'output/sz_jlc_lcd_driver.lib', 'output/sz_jlc_lcd_driver.dcm'],

  # [CAT_SMD_LEVEL_SHIFTER_SHIFTER,  'output/sz_jlc_level_shifter_shifter.lib', 'output/sz_jlc_level_shifter_shifter.dcm'],
  # [CAT_SMD_LINEAR_VOLTAGE_REGULATOR_CHIP,  'output/sz_jlc_linear_voltage_regulator_chip.lib', 'output/sz_jlc_linear_voltage_regulator_chip.dcm'],
  # [CAT_SMD_LOGIC_CHIP_,  'output/sz_jlc_logic_chip_.lib', 'output/sz_jlc_logic_chip_.dcm'],
  # [CAT_SMD_LOGIC_CHIP_4000_SERIES,  'output/sz_jlc_logic_chip_4000_series.lib', 'output/sz_jlc_logic_chip_4000_series.dcm'],
  # [CAT_SMD_LOGIC_CHIP_74_SERIES,  'output/sz_jlc_logic_chip_74_series.lib', 'output/sz_jlc_logic_chip_74_series.dcm'],
  # [CAT_SMD_LOW_NOISE_OP_AMP,  'output/sz_jlc_low_noise_op_amp.lib', 'output/sz_jlc_low_noise_op_amp.dcm'],
  # [CAT_SMD_LOW_POWER_OP_AMP,  'output/sz_jlc_low_power_op_amp.lib', 'output/sz_jlc_low_power_op_amp.dcm'],
  # [CAT_SMD_LVDS_CHIP,  'output/sz_jlc_lvds_chip.lib', 'output/sz_jlc_lvds_chip.dcm'],
  # [CAT_SMD_MAGNETIC_BEADS,  'output/sz_jlc_magnetic_beads.lib', 'output/sz_jlc_magnetic_beads.dcm'],
  # [CAT_SMD_MAGNETIC_SENSOR,  'output/sz_jlc_magnetic_sensor.lib', 'output/sz_jlc_magnetic_sensor.dcm'],

  # [CAT_SMD_MOS_DRIVE,  'output/sz_jlc_mos_drive.lib', 'output/sz_jlc_mos_drive.dcm'],
  # [CAT_SMD_MOS_FIELD_EFFECT_TUBE,  'output/sz_jlc_mos_field_effect_tube.lib', 'output/sz_jlc_mos_field_effect_tube.dcm'],
  # [CAT_SMD_MOTOR_DRIVER,  'output/sz_jlc_motor_driver.lib', 'output/sz_jlc_motor_driver.dcm'],
  # [CAT_SMD_MULTI_FREQUENCY_OSCILLATOR,  'output/sz_jlc_multi_frequency_oscillator.lib', 'output/sz_jlc_multi_frequency_oscillator.dcm'],
  # [CAT_SMD_NETWORK_PORT_TRANSFORMER,  'output/sz_jlc_network_port_transformer.lib', 'output/sz_jlc_network_port_transformer.dcm'],
  # [CAT_SMD_NIOBIUM_OXIDE_CAPACITOR,  'output/sz_jlc_niobium_oxide_capacitor.lib', 'output/sz_jlc_niobium_oxide_capacitor.dcm'],
  # [CAT_SMD_NTC_RESISTOR,  'output/sz_jlc_ntc_resistor.lib', 'output/sz_jlc_ntc_resistor.dcm'],
  # [CAT_SMD_OP_AMP_GENERAL_OP_AMP,  'output/sz_jlc_op_amp_general_op_amp.lib', 'output/sz_jlc_op_amp_general_op_amp.dcm'],
  # [CAT_SMD_OP_AMP_PRECISION_OP_AMP,  'output/sz_jlc_op_amp_precision_op_amp.lib', 'output/sz_jlc_op_amp_precision_op_amp.dcm'],
  # [CAT_SMD_OPTICAL_SENSORS,  'output/sz_jlc_optical_sensors.lib', 'output/sz_jlc_optical_sensors.dcm'],
  # [CAT_SMD_OPTOCOUPLER,  'output/sz_jlc_optocoupler.lib', 'output/sz_jlc_optocoupler.dcm'],
  # [CAT_SMD_PASSIVE_CRYSTAL_RESONATOR,  'output/sz_jlc_passive_crystal_resonator.lib', 'output/sz_jlc_passive_crystal_resonator.dcm'],
  # [CAT_SMD_PHOTOELECTRIC_SOLID_STATE_RELAY,  'output/sz_jlc_photoelectric_solid_state_relay.lib', 'output/sz_jlc_photoelectric_solid_state_relay.dcm'],
  # [CAT_SMD_PHOTOELECTRIC_SWITCH,  'output/sz_jlc_photoelectric_switch.lib', 'output/sz_jlc_photoelectric_switch.dcm'],
  # [CAT_SMD_PHOTOELECTRIC_TRIAC,  'output/sz_jlc_photoelectric_triac.lib', 'output/sz_jlc_photoelectric_triac.dcm'],
  # [CAT_SMD_PORT_EXPANSION_CHIP,  'output/sz_jlc_port_expansion_chip.lib', 'output/sz_jlc_port_expansion_chip.dcm'],
  # [CAT_SMD_POSITION_SENSOR,  'output/sz_jlc_position_sensor.lib', 'output/sz_jlc_position_sensor.dcm'],
  # [CAT_SMD_POWER_INDUCTOR,  'output/sz_jlc_power_inductor.lib', 'output/sz_jlc_power_inductor.dcm'],
  # [CAT_SMD_POWER_MONITORING_CHIP,  'output/sz_jlc_power_monitoring_chip.lib', 'output/sz_jlc_power_monitoring_chip.dcm'],
  # [CAT_SMD_POWER_SWITCH_CHIP,  'output/sz_jlc_power_switch_chip.lib', 'output/sz_jlc_power_switch_chip.dcm'],
  # [CAT_SMD_PRESSURE_SENSOR,  'output/sz_jlc_pressure_sensor.lib', 'output/sz_jlc_pressure_sensor.dcm'],
  # [CAT_SMD_PROFESSIONAL_POWER_MANAGEMENT_PMIC,  'output/sz_jlc_professional_power_management_pmic.lib', 'output/sz_jlc_professional_power_management_pmic.dcm'],
  # [CAT_SMD_PTC_RESETTABLE_FUSE,  'output/sz_jlc_ptc_resettable_fuse.lib', 'output/sz_jlc_ptc_resettable_fuse.dcm'],
  # [CAT_SMD_REAL_TIME_CLOCK_CHIP,  'output/sz_jlc_real_time_clock_chip.lib', 'output/sz_jlc_real_time_clock_chip.dcm'],
  # [CAT_SMD_RECTIFIER_BRIDGE,  'output/sz_jlc_rectifier_bridge.lib', 'output/sz_jlc_rectifier_bridge.dcm'],
  # [CAT_SMD_RESISTOR_NETWORK,  'output/sz_jlc_resistor_network.lib', 'output/sz_jlc_resistor_network.dcm'],
  # [CAT_SMD_RF_AMPLIFIER,  'output/sz_jlc_rf_amplifier.lib', 'output/sz_jlc_rf_amplifier.dcm'],
  # [CAT_SMD_RF_ATTENUATOR,  'output/sz_jlc_rf_attenuator.lib', 'output/sz_jlc_rf_attenuator.dcm'],
  # [CAT_SMD_RF_CARD_CHIP,  'output/sz_jlc_rf_card_chip.lib', 'output/sz_jlc_rf_card_chip.dcm'],
  # [CAT_SMD_RF_COUPLER,  'output/sz_jlc_rf_coupler.lib', 'output/sz_jlc_rf_coupler.dcm'],
  # [CAT_SMD_RF_DETECTOR,  'output/sz_jlc_rf_detector.lib', 'output/sz_jlc_rf_detector.dcm'],
  # [CAT_SMD_RF_FILTER,  'output/sz_jlc_rf_filter.lib', 'output/sz_jlc_rf_filter.dcm'],
  # [CAT_SMD_RF_MIXER,  'output/sz_jlc_rf_mixer.lib', 'output/sz_jlc_rf_mixer.dcm'],
  # [CAT_SMD_RF_SWITCH,  'output/sz_jlc_rf_switch.lib', 'output/sz_jlc_rf_switch.dcm'],
  # [CAT_SMD_RS232_CHIP,  'output/sz_jlc_rs232_chip.lib', 'output/sz_jlc_rs232_chip.dcm'],
  # [CAT_SMD_RS485_RS422_CHIP,  'output/sz_jlc_rs485_rs422_chip.lib', 'output/sz_jlc_rs485_rs422_chip.dcm'],
  # [CAT_SMD_SCHOTTKY_DIODE,  'output/sz_jlc_schottky_diode.lib', 'output/sz_jlc_schottky_diode.dcm'],
  # [CAT_SMD_SDRAM_MEMORY,  'output/sz_jlc_sdram_memory.lib', 'output/sz_jlc_sdram_memory.dcm'],
  # [CAT_SMD_SECURITY_VERIFICATION_ENCRYPTION_CHIP,  'output/sz_jlc_security_verification_encryption_chip.lib', 'output/sz_jlc_security_verification_encryption_chip.dcm'],
  # [CAT_SMD_SENSOR_INTERFACE_CHIP,  'output/sz_jlc_sensor_interface_chip.lib', 'output/sz_jlc_sensor_interface_chip.dcm'],
  # [CAT_SMD_SERIAL_INTERFACE,  'output/sz_jlc_serial_interface.lib', 'output/sz_jlc_serial_interface.dcm'],
  # [CAT_SMD_SHIFT_REGISTER,  'output/sz_jlc_shift_register.lib', 'output/sz_jlc_shift_register.dcm'],
  # [CAT_SMD_SIGNAL_BUFFERS_REPEATERS_DISTRIBUTORS,  'output/sz_jlc_signal_buffers_repeaters_distributors.lib', 'output/sz_jlc_signal_buffers_repeaters_distributors.dcm'],
  # [CAT_SMD_SIGNAL_SWITCHES_MULTIPLEXERS_DECODERS,  'output/sz_jlc_signal_switches_multiplexers_decoders.lib', 'output/sz_jlc_signal_switches_multiplexers_decoders.dcm'],
  # [CAT_SMD_ACTIVE_CRYSTAL_OSCILLATOR,  'output/sz_jlc_smd_active_crystal_oscillator.lib', 'output/sz_jlc_smd_active_crystal_oscillator.dcm'],
  # [CAT_SMD_SOLID_ELECTROLYTIC_CAPACITOR,  'output/sz_jlc_solid_electrolytic_capacitor.lib', 'output/sz_jlc_solid_electrolytic_capacitor.dcm'],
  # [CAT_SMD_SOUND_SURFACE_RESONATOR_SAW,  'output/sz_jlc_sound_surface_resonator_saw.lib', 'output/sz_jlc_sound_surface_resonator_saw.dcm'],
  # [CAT_SMD_SPECIAL_FUNCTION_AMPLIFIER,  'output/sz_jlc_special_function_amplifier.lib', 'output/sz_jlc_special_function_amplifier.dcm'],
  # [CAT_SMD_SPECIAL_FUNCTION_DRIVEN,  'output/sz_jlc_special_function_driven.lib', 'output/sz_jlc_special_function_driven.dcm'],
  # [CAT_SMD_SRAM_MEMORY,  'output/sz_jlc_sram_memory.lib', 'output/sz_jlc_sram_memory.dcm'],
  # [CAT_SMD_SWITCHING_DIODE,  'output/sz_jlc_switching_diode.lib', 'output/sz_jlc_switching_diode.dcm'],
  # [CAT_SMD_SWITCHING_POWER_CHIP,  'output/sz_jlc_switching_power_chip.lib', 'output/sz_jlc_switching_power_chip.dcm'],
  # [CAT_SMD_TACT_SWITCH,  'output/sz_jlc_tact_switch.lib', 'output/sz_jlc_tact_switch.dcm'],
  # [CAT_SMD_TANTALUM_CAPACITOR,  'output/sz_jlc_tantalum_capacitor.lib', 'output/sz_jlc_tantalum_capacitor.dcm'],
  # [CAT_SMD_TEMPERATURE_AND_HUMIDITY_SENSOR,  'output/sz_jlc_temperature_and_humidity_sensor.lib', 'output/sz_jlc_temperature_and_humidity_sensor.dcm'],
  # [CAT_SMD_TEMPERATURE_SENSOR,  'output/sz_jlc_temperature_sensor.lib', 'output/sz_jlc_temperature_sensor.dcm'],
  # [CAT_SMD_THYRISTOR,  'output/sz_jlc_thyristor.lib', 'output/sz_jlc_thyristor.dcm'],
  # [CAT_SMD_TIME_BASE_INTEGRATED_CHIP,  'output/sz_jlc_time_base_integrated_chip.lib', 'output/sz_jlc_time_base_integrated_chip.dcm'],
  # [CAT_SMD_TOUCH_CHIP,  'output/sz_jlc_touch_chip.lib', 'output/sz_jlc_touch_chip.dcm'],
  # [CAT_SMD_TOUCH_SCREEN_CONTROLLER,  'output/sz_jlc_touch_screen_controller.lib', 'output/sz_jlc_touch_screen_controller.dcm'],
  # [CAT_SMD_TRIGGER_DIODE,  'output/sz_jlc_trigger_diode.lib', 'output/sz_jlc_trigger_diode.dcm'],
  # [CAT_SMD_TRIGGER,  'output/sz_jlc_trigger.lib', 'output/sz_jlc_trigger.dcm'],
  # [CAT_SMD_TRIODE_DIGITAL_TRIODE,  'output/sz_jlc_triode_digital_triode.lib', 'output/sz_jlc_triode_digital_triode.dcm'],
  # [CAT_SMD_TRIODE,  'output/sz_jlc_triode.lib', 'output/sz_jlc_triode.dcm'],
  # [CAT_SMD_TVS_DIODE,  'output/sz_jlc_tvs_diode.lib', 'output/sz_jlc_tvs_diode.dcm'],
  # [CAT_SMD_ULTRA_FAST_RECOVERY_DIODE,  'output/sz_jlc_ultra_fast_recovery_diode.lib', 'output/sz_jlc_ultra_fast_recovery_diode.dcm'],
  # [CAT_SMD_USB_CHIP,  'output/sz_jlc_usb_chip.lib', 'output/sz_jlc_usb_chip.dcm'],
  # [CAT_SMD_VARICAP_DIODE,  'output/sz_jlc_varicap_diode.lib', 'output/sz_jlc_varicap_diode.dcm'],
  # [CAT_SMD_VARISTOR,  'output/sz_jlc_varistor.lib', 'output/sz_jlc_varistor.dcm'],
  # [CAT_SMD_VIDEO_AND_AUDIO_INTERFACE_CHIP,  'output/sz_jlc_video_and_audio_interface_chip.lib', 'output/sz_jlc_video_and_audio_interface_chip.dcm'],
  # [CAT_SMD_VIDEO_FILTER_DRIVER,  'output/sz_jlc_video_filter_driver.lib', 'output/sz_jlc_video_filter_driver.dcm'],
  # [CAT_SMD_VOLTAGE_COMPARATOR,  'output/sz_jlc_voltage_comparator.lib', 'output/sz_jlc_voltage_comparator.dcm'],
  # [CAT_SMD_VOLTAGE_REFERENCE_CHIP,  'output/sz_jlc_voltage_reference_chip.lib', 'output/sz_jlc_voltage_reference_chip.dcm'],
  # [CAT_SMD_WIRELESS_TRANSCEIVER_CHIP,  'output/sz_jlc_wireless_transceiver_chip.lib', 'output/sz_jlc_wireless_transceiver_chip.dcm'],

  # # [CAT_SMD_SECOND_CLASSIFICATION_OF_ENGINEERING_DEPARTMENT_DATA,  'output/sz_jlc_second_classification_of_engineering_department_data.lib', 'output/sz_jlc_second_classification_of_engineering_department_data.dcm'],
]

def lookup_drawing_by_category(component_category):
  output = list(lookup_master_table_by_category(component_category))
  try:
    if (len(output) == 1):
      return output[0][5]
    else:
      raise 'lookup_drawing_by_category error'
  except Exception as e:
    pprint('lookup_drawing_by_category error')
    raise e
    pass


def lookup_master_table_by_category(component_category):
  return list(filter(lambda x: x[0]==component_category, master_table))