#!/usr/bin/env python3

import os,sys,re
from pprint import pprint

COL_NUM_COMPONENT_ID=0
COL_NUM_COMPONENT_NAME=1
COL_NUM_COMPONENT_CATEGORY=2
COL_NUM_COMPONENT_FOOTPRINT=3
COL_NUM_COMPONENT_SOLDER_PAD=4
COL_NUM_COMPONENT_MANUFACTURER=5
COL_NUM_COMPONENT_LIB_TYPE=6

COL_LIST_COMPONET_FIELD=[
  COL_NUM_COMPONENT_ID,
  COL_NUM_COMPONENT_NAME,
  COL_NUM_COMPONENT_CATEGORY,
  COL_NUM_COMPONENT_FOOTPRINT,
  COL_NUM_COMPONENT_SOLDER_PAD,
  COL_NUM_COMPONENT_MANUFACTURER,
  COL_NUM_COMPONENT_LIB_TYPE
]